import json

NOTEBOOK_PATH = r"c:\Users\biasb\Desktop\pygame_fundamentals_EXPLAINATION.ipynb"

new_sources = [
    # 0. Installs
    [
        "# 1. I-install ang pygame library gamit ang 'pip install'. Kailangan ito para magamit natin ang Pygame tools.\n",
        "!pip install pygame\n"
    ],
    # 1. Initialization
    [
        "# 1. I-import ang pygame library para gumana ang mga tools nito sa ating code.\n",
        "import pygame\n",
        "\n",
        "# 2. Siguraduhing i-initialize (pygame.init) ang lahat ng modules (display, sound, etc.) bago gumamit ng kahit ano.\n",
        "pygame.init()\n",
        "\n",
        "# 3. Mag-print sa console para malaman kung successful ang initialization.\n",
        "print(\"Pygame initialized successfully!\")\n",
        "# 4. I-print din kung anong versiyon ng pygame ang kasalukuyang ginagamit natin.\n",
        "print(f\"Pygame version: {pygame.ver}\")\n"
    ],
    # 2. Display Window
    [
        "# 1. I-import ang main pygame library.\n",
        "import pygame\n",
        "# 2. Simulan agad ang initialization logic ng pyame systems.\n",
        "pygame.init()\n",
        "\n",
        "# 3. I-define ang variable para sa lapad ng game screen (800 pixels).\n",
        "SCREEN_WIDTH = 800\n",
        "# 4. I-define ang variable para sa taas ng game screen (600 pixels).\n",
        "SCREEN_HEIGHT = 600\n",
        "\n",
        "# 5. Gamitin ang pygame.display.set_mode para gawin at ilabas ang mismong window ng game.\n",
        "screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))\n",
        "# 6. I-set ang window caption (yung title sa may title bar) pampaganda at pang-identify.\n",
        "pygame.display.set_caption(\"My First Pygame Window\")\n",
        "\n",
        "# 7. Kulayan ang buong background ng screen ng napiling RGB color tuple nang sabay-sabay.\n",
        "screen.fill((30, 30, 60))  # Dark blue-gray background\n",
        "# 8. Gamitin ang display.flip() para ma-execute at mag-update ang mismong visual sa monitor mo.\n",
        "pygame.display.flip()\n",
        "\n",
        "# 9. Dahil wala pang loop, pipigilan muna natin magsara ang script for 3000 milliseconds (3 seconds).\n",
        "pygame.time.wait(3000)\n",
        "# 10. Kapag tapos na ang wait timer, malinis na isasara ang pygame window.\n",
        "pygame.quit()\n",
        "# 11. I-print na opisyal na nasara ang window natin.\n",
        "print(\"Window closed.\")\n"
    ],
    # 3. Colors
    [
        "# 1. Ang pag de-define ng mga commonly-used na kulay bilang ALL_CAPS constants ay good practice.\n",
        "# 2. Ang Tuple na (255, 255, 255) ay fully saturated Red, Green, and Blue kaya ito'y nagiging PUTI.\n",
        "WHITE  = (255, 255, 255)\n",
        "# 3. Dahil (0, 0, 0) lahat walang kulay na pinaghalo kaya ITIM ito.\n",
        "BLACK  = (0,   0,   0)\n",
        "# 4. Naka-max yung unang index (Red) habang zero ang iba kaya PULA.\n",
        "RED    = (255, 0,   0)\n",
        "# 5. Naka-max sa gitnang tuple channel ang number kaya BERDE.\n",
        "GREEN  = (0,   255, 0)\n",
        "# 6. Naka-max dulo therefore ASUL dahil siya ang third slot na RGB.\n",
        "BLUE   = (0,   0,   255)\n",
        "# 7. Red + Green combinations forms the YELLOW hue (255,255,0).\n",
        "YELLOW = (255, 255, 0)\n",
        "\n",
        "# 8. Silipin na natin if variable properly mapped white color map output natin!\n",
        "print(f\"White: {WHITE}\")\n",
        "# 9. Test dynamic purple shade using its specific coordinate mixtures as 128 red at 128 b.\n",
        "print(f\"Custom Purple: {(128, 0, 128)}\")\n"
    ],
    # 4. Shapes
    [
        "# 1. Start setup for pygame app.\n",
        "import pygame\n",
        "# 2. Activate features nito bago mag draw.\n",
        "pygame.init()\n",
        "\n",
        "# 3. Window resolution surface initialize.\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "# 4. Window top label title format.\n",
        "pygame.display.set_caption(\"Drawing Shapes\")\n",
        "# 5. Wash drawing point board clear natin by grey-blue shade background fill command.\n",
        "screen.fill((30, 30, 60))\n",
        "\n",
        "# 6. Draw functions format logic using surface screen call point destination surface.\n",
        "# --- Draw a filled rectangle ---\n",
        "# pygame.draw.rect(surface, color, (x, y, width, height))\n",
        "# 7. Kulay pink (255...100) iguhit rect as origin (50,50) at lapad 200, taas na 100 na filled.\n",
        "pygame.draw.rect(screen, (255, 100, 100), (50, 50, 200, 100))\n",
        "\n",
        "# 8. Dito dahil may 3 sa huli, siya'y outline na ng rectangle.\n",
        "# --- Draw an outlined rectangle ---\n",
        "pygame.draw.rect(screen, (100, 255, 100), (300, 50, 200, 100), 3)  # 3px border\n",
        "\n",
        "# 9. Circle form parameter shape need point coordinates x at y para posisyon plus target radius perimeter.\n",
        "# --- Draw a filled circle ---\n",
        "# pygame.draw.circle(surface, color, (center_x, center_y), radius)\n",
        "# 10. Asul shade round circle with radius na kasinglaki 80!\n",
        "pygame.draw.circle(screen, (100, 100, 255), (150, 300), 80)\n",
        "\n",
        "# 11. Connecting dots tuwid na guhit gamit coordinates form.\n",
        "# --- Draw a line ---\n",
        "# pygame.draw.line(surface, color, (start_x, start_y), (end_x, end_y), width)\n",
        "# 12. Papuntang bottom kanan start of 350x250 ends straight directly towards point 700x400.\n",
        "pygame.draw.line(screen, (255, 255, 0), (350, 250), (700, 400), 4)\n",
        "\n",
        "# 13. Complex connected node poly triangle generation code loop connecting.\n",
        "# --- Draw a polygon (triangle) ---\n",
        "# 14. 3 points arrays given to create visual rendering triangle connection via points values data arrays given.\n",
        "pygame.draw.polygon(screen, (255, 0, 255), [(600, 100), (700, 250), (500, 250)])\n",
        "\n",
        "# 15. Flip call renders current logic screen frames para makita!\n",
        "pygame.display.flip()\n",
        "# 16. Stop waiting the codes line processes delay para visual makita execution time of 4 seconds na hindi magsara.\n",
        "pygame.time.wait(4000)\n",
        "# 17. Pygame cleanup closing memory un allocations process routine script call execute exit routine commands shutdown process command close system tasks function execution shutdown exit execution interface function run system stop!\n",
        "pygame.quit()\n",
        "# 18. Signal text output on IDE text window print function.\n",
        "print(\"Shapes demo closed.\")\n"
    ],
    # 5. Game loop
    [
        "# 1. Unang gawin syempre is to import.\n",
        "import pygame\n",
        "# 2. Need i-start start ang modules ng pygame bago simulan.\n",
        "pygame.init()\n",
        "\n",
        "# 3. Standard dimension windows surface create call natin initialization.\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "# 4. Mag define lang ng title bar na Basic Game Loop string.\n",
        "pygame.display.set_caption(\"Basic Game Loop\")\n",
        "# 5. Para ma limit ang loop per frames speed variable object gagamitin fps delay logic check reference update system tick control.\n",
        "clock = pygame.time.Clock()\n",
        "\n",
        "# 6. The boolean value condition na hahayaang continually check up logic process infinite on going the execution process until its flagged mapigilan false!\n",
        "running = True\n",
        "# 7. The main brain engine flow update execution step of every loop start point block frame loop per cycle iteration logic process trigger.\n",
        "while running:\n",
        "    # 8. Loop handle events polling updates mouse keyboard commands input event logic systems fetch ng list operations ng tao interact.\n",
        "    # ─── 1. EVENT HANDLING ───\n",
        "    for event in pygame.event.get():\n",
        "        # 9. Kung yung event action nila is yung mismong Exit System Window Command Quit Trigger Event logic handler operations block call actions trigger condition control logic check process run...\n",
        "        if event.type == pygame.QUIT:      # User clicked the X button\n",
        "            # 10. Baguhin sa False logic ng execution state para the next iter mamamatay loop natin loop condition breaks false process trigger stop flag logic false trigger action control logic assignment variable flag status.\n",
        "            running = False\n",
        "\n",
        "    # 11. State computation para variables location coordinates na gagawin the game objects updates per logic computations run!\n",
        "    # ─── 2. UPDATE (game logic) ───\n",
        "    # (nothing to update in this basic example)\n",
        "\n",
        "    # 12. Mag papahid burahin background using basic standard colors fill the display update display draw calls sequence.\n",
        "    # ─── 3. DRAW / RENDER ───\n",
        "    screen.fill((30, 30, 60))              # Clear the screen each frame\n",
        "    # 13. Output circle center frame per cycle loop loop loop sequence!\n",
        "    pygame.draw.circle(screen, (0, 200, 255), (400, 300), 50)\n",
        "    # 14. Important is end update memory window UI swap buffers front rendering the back buffers output drawing call execution trigger render commands push flush system data update frame show sequence method interface output loop cycle update map the pixels sequence draw command.\n",
        "    pygame.display.flip()                  # Show everything\n",
        "\n",
        "    # 15. The FPS framerates control loop tick execution time management speed check process parameter pass arg system lock command limit method constraint system cycle operations cap 60 limit call the interface command parameter logic values.\n",
        "    clock.tick(60)                         # Cap at 60 FPS\n",
        "\n",
        "# 16. Process memory shut close release memory functions end loop script shutdown command exit tasks interface functions.\n",
        "pygame.quit()\n",
        "# 17. Notify success command message execution sequence finished successfully.\n",
        "print(\"Game loop ended.\")\n"
    ],
    # 6. Event Handling
    [
        "# 1. Need the package library for python game module framework initialization point access call routines start map.\n",
        "import pygame\n",
        "# 2. Start default basic system libraries loads and map components function ready values initialization system routine setup!\n",
        "pygame.init()\n",
        "\n",
        "# 3. Load surface monitor container frame context mapping view display values width w and length parameters value data.\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "# 4. Header GUI label windows title text display param set up!\n",
        "pygame.display.set_caption(\"Event Handling Demo\")\n",
        "# 5. Framerate limits system handler control object!\n",
        "clock = pygame.time.Clock()\n",
        "\n",
        "# 6. Logic variables the values that represents circle player characters point on axis x at coordinate ang horizontal y is point position starting map locations value default variable data.\n",
        "# Circle position (will be moved by arrow keys)\n",
        "x, y = 400, 300\n",
        "# 7. Gaano kalaki iaadjust points velocity every iteration tick per process ng pindot updates!\n",
        "speed = 5\n",
        "# 8. Starter color tuple color code object value definition rgb param logic default values format data type points variables constant tuple format mapping!\n",
        "color = (0, 200, 255)\n",
        "\n",
        "# 9. Flag natin indicator true to continually function loop logic command check boolean condition param check state variable param value parameter value reference data structure variables conditions logic operations process variable data logic value param assignment var object check data flag state command variable object var.\n",
        "running = True\n",
        "# 10. Frame cycle updates begin now!\n",
        "while running:\n",
        "    # 11. Loop to array check events array map commands logic parameters value event array command input query events call user inputs triggers map.\n",
        "    for event in pygame.event.get():\n",
        "        # 12. Event checks check system windows operation interrupt trigger operation logic command control map window close action button check command loop array process logic the trigger interface condition control block logic operations system mapping values check condition parameter function operation checks system operations close action event parameter.\n",
        "        if event.type == pygame.QUIT:\n",
        "            # 13. Map to false close while loop the frame loops next checks false state mapping process state loop assignment logic assign control data map variable assignment.\n",
        "            running = False\n",
        "\n",
        "        # 14. Check key switch is trigger DOWN (Press operation map action input user event keyboard function type keys trigger push command logic trigger block if checks parameter variable constant condition the map parameters value constants function calls parameters value mapping process data type map control type array condition key check process data object parameter value mapping conditional command condition data map mapping map.\n",
        "        # Single key press event — change color on SPACE\n",
        "        if event.type == pygame.KEYDOWN:\n",
        "            # 15. Tingnan if SPACE character character key string mapping match key event mapped object system constants constant parameters boolean operation compare function values matching match operation parameters function call operations conditions checks map comparison command check control logic variables constants checks condition constants check condition logic map condition checks data mapping parameters compare operation block process logic conditions keys condition control control map type loop checks variables command logic checks mapping.\n",
        "            if event.key == pygame.K_SPACE:\n",
        "                # 16. Kapag ganun switch out kulay parameter value map the update reference param assignment value reference value values object mapping update command mapping data values map variable object the constants mapping object parameters condition values operations variables map condition logic map assignment value logic mappings values checks assignments param values ternary condition value data types object mapping update map update assignment mapping values variables command data object map process update assignment command assignment param value data variables.\n",
        "                # Toggle between cyan and red\n",
        "                color = (255, 80, 80) if color == (0, 200, 255) else (0, 200, 255)\n",
        "\n",
        "    # 17. The keys boolean arrays checking continuously holding check array update array array method continuous hold flags key down inputs loop process system function mapped checking loop flag continuous parameter checks values keys flags flags continuous logic logic loop control mapping conditions values function calls control commands.\n",
        "    # Continuous key press — smooth movement with arrow keys\n",
        "    keys = pygame.key.get_pressed()\n",
        "    # 18. Ang pag check na flag left means update parameters x to specific minus direction movement logic condition.\n",
        "    if keys[pygame.K_LEFT]:\n",
        "        x -= speed\n",
        "    # 19. Kapag array key right flag is ok is active then x increases horizontal axes.\n",
        "    if keys[pygame.K_RIGHT]:\n",
        "        x += speed\n",
        "    # 20. Param up direction arrow values the map check variable flag check operation map y logic minus operation move top process condition blocks process parameters command checks function logical operations controls checks checks update.\n",
        "    if keys[pygame.K_UP]:\n",
        "        y -= speed\n",
        "    # 21. Ang pababa the key is mapping of add up on the value param logic map y mapping command data type param assignment control flag block checks update check data logic control block checks update block.\n",
        "    if keys[pygame.K_DOWN]:\n",
        "        y += speed\n",
        "\n",
        "    # 22. Maglagay color to overwrite parameters logic buffer.\n",
        "    # Draw\n",
        "    screen.fill((30, 30, 60))\n",
        "    # 23. Doon na mag drawing exact update parameter x map map mapped target parameter point surface process command draw call variable the constant shape calls operations parameters parameters type rendering.\n",
        "    pygame.draw.circle(screen, color, (x, y), 30)\n",
        "    # 24. Pagsigla screen surface para makita monitor the user map process commands flip triggers update functions parameter functions system buffer mapping render parameter values command flip display object calls display rendering.\n",
        "    pygame.display.flip()\n",
        "    # 25. Update object cycle FPS control constraints limitation control logic limit loops operations the loop checks tick value frame limitation cycle mapping cycle limitation method parameters.\n",
        "    clock.tick(60)\n",
        "\n",
        "# 26. Cleanup process closing operations map termination system stop logic variable object command execution interface tasks stop sequence unmap memory clear operations.\n",
        "pygame.quit()\n",
        "# 27. Log value update check demo script console.\n",
        "print(\"Event demo closed.\")\n"
    ],
    # 7. Images Loading
    [
        "# 1. Initialize operations the objects loop map process mapping module system map commands system parameter type library check map variables.\n",
        "import pygame\n",
        "pygame.init()\n",
        "\n",
        "# 2. Standard Surface Display creation map parameters.\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "pygame.display.set_caption(\"Image Loading Demo\")\n",
        "\n",
        "# 3. A test function na ittry using exception handle na mag iimport the parameters variable object function image from the given file source address check the process logic type mapping.\n",
        "# --- Loading an image ---\n",
        "# Replace with your actual image path\n",
        "try:\n",
        "    # 4. Kukuha from direct folder reference then i-convert ng format for alpha handling efficiency loop processes control map the variable check parameter condition.\n",
        "    image = pygame.image.load(\"src/assets/sprites/rayquaza/idle/rayquaza_0.png\").convert_alpha()\n",
        "    \n",
        "    # 5. Eto ay technique pag zoom image 2x base parameter ng object height command na values variable reference format structure methods of value assignment scaling objects update object assignment command process operation.\n",
        "    # Scale the image to 2x its original size\n",
        "    image = pygame.transform.scale(image, (image.get_width() * 2, image.get_height() * 2))\n",
        "    \n",
        "    # 6. Para gawing invisible yung plain blue constant values command mapping variable check parameters update operations.\n",
        "    # Remove background color (color key)\n",
        "    image.set_colorkey((112, 154, 209))\n",
        "    \n",
        "    # 7. Burahin muna current target buffer map output color object map commands logic mapping parameter command loop calls variables value execution sequence command variable control checks loops.\n",
        "    screen.fill((30, 30, 60))\n",
        "    # 8. Importante ang Blit, ibig sabihin ipapahid na dito the modified mapping variable memory variables parameter system rendering data surface sa parameters parameter parameter function system output sequence values mapping target coordinates form variable interface point target target variable target the map output target system format parameter target execution rendering map sequence variable variables output variable buffer the mapped source.\n",
        "    screen.blit(image, (300, 200))  # Draw image at position (300, 200)\n",
        "    # 9. At syempre trigger call the flip method system output display buffer sequence mapping point values output.\n",
        "    pygame.display.flip()\n",
        "    # 10. Pause 4 sec wait check parameter system pause operations checks wait cycle loops logic checks variables target time wait process parameter logic checks system variables wait operations.\n",
        "    pygame.time.wait(4000)\n",
        "    \n",
        "# 11. Optional para pag error di kita nakita path.\n",
        "except FileNotFoundError:\n",
        "    print(\"Image file not found! Make sure the path is correct.\")\n",
        "    print(\"Expected: src/assets/sprites/rayquaza/idle/rayquaza_0.png\")\n",
        "\n",
        "# 12. Sequence close quit termination routines mapping execution functions stop tasks.\n",
        "pygame.quit()\n",
        "# 13. System check message outputs variable logging format message.\n",
        "print(\"Image demo closed.\")\n"
    ],
    # 8. Text Rendering
    [
        "# 1. Import map modules variable objects logic dependencies mapping function.\n",
        "import pygame\n",
        "pygame.init()\n",
        "\n",
        "# 2. Gumawa windows command screen the mapping GUI.\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "pygame.display.set_caption(\"Text Rendering Demo\")\n",
        "# 3. Fill variable the target data map param value reference execution output variables format memory display surface fill function array the assignment command object array system the tuple color value system array update sequence map the process parameter map variable values parameter checks assignment string system system sequence operations value string target process string operation values functions parameter target system mapping mapping update command the variable targets mapping update operation data the parameters form mapping targets.\n",
        "screen.fill((30, 30, 60))\n",
        "\n",
        "# 4. Pygame way ng pag import texts fonts from variables object from object fonts system format map system arial form process format rendering command form system the assignment logic values the variable target operations operations mapping type objects format control the assignment operations type parameters condition checks variables format.\n",
        "# Create font objects\n",
        "title_font = pygame.font.SysFont(\"Arial\", 48, bold=True)\n",
        "body_font  = pygame.font.SysFont(\"Arial\", 28)\n",
        "\n",
        "# 5. Using the render type format command param mapping from variable font map value string memory variable target object command type mapping format function surface map assignment type parameters form variables string variable parameters type parameters the update loop string checks variables data logic loops.\n",
        "# Render text surfaces\n",
        "title = title_font.render(\"Pygame Text Demo\", True, (255, 255, 255))\n",
        "line1 = body_font.render(\"This is rendered using pygame.font\", True, (0, 200, 255))\n",
        "line2 = body_font.render(\"Press any key or close the window.\", True, (200, 200, 200))\n",
        "\n",
        "# 6. Ang BLITTING (Pag ididikit ang drawing text as image data). \n",
        "# Blit text onto the screen\n",
        "screen.blit(title, (200, 150))\n",
        "screen.blit(line1, (180, 250))\n",
        "screen.blit(line2, (180, 300))\n",
        "\n",
        "# 7. Updates map values format points rendering surface front display visual sequence map functions parameter system checks target.\n",
        "pygame.display.flip()\n",
        "# 8. Limit lock loops condition wait the object array array values string condition lock system map.\n",
        "pygame.time.wait(4000)\n",
        "# 9. End process type operations parameters execution sequence loops variables operations commands formats parameters values strings.\n",
        "pygame.quit()\n",
        "print(\"Text demo closed.\")\n"
    ],
    # 9. Clock FPS
    [
        "# 1. Setup execution sequence modules variables formatting conditions type object operations functions.\n",
        "import pygame\n",
        "pygame.init()\n",
        "\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "pygame.display.set_caption(\"FPS Demo\")\n",
        "# 2. Object variables array mapping the target assignments clock mapping values the functions values type parameters the values conditions formats command parameter logic checks memory type type parameters command mapping function values formats param parameters format process check format assignment mapping values object map type values assignments values form.\n",
        "clock = pygame.time.Clock()\n",
        "font = pygame.font.SysFont(\"Arial\", 28)\n",
        "\n",
        "# 3. Track horizontal mapping updates loop conditions mapping loop objects variable command variables string array assignment logic object system target functions data types arrays format strings.\n",
        "x = 0  # Moving rectangle position\n",
        "\n",
        "# 4. State loops execution map array mapping loop mapping string commands logic condition flags operations condition variable variables check logic condition.\n",
        "running = True\n",
        "while running:\n",
        "    for event in pygame.event.get():\n",
        "        if event.type == pygame.QUIT:\n",
        "            running = False\n",
        "\n",
        "    # 5. Idagdag per object form variables the point arrays loops conditions updates format operations array variable format logic values parameter condition mappings strings point array loops mapping variables object check format check data operations command strings check.\n",
        "    # Move a rectangle across the screen\n",
        "    x += 3\n",
        "    if x > 800:\n",
        "        x = -100\n",
        "\n",
        "    screen.fill((30, 30, 60))\n",
        "    pygame.draw.rect(screen, (0, 200, 255), (x, 260, 100, 80))\n",
        "\n",
        "    # 6. Render FPS target memory string map function formats type form mapping values mapping strings mapping type the parameter formats checks functions variables data array array object form format checks strings values string format check map assignment the mapping commands parameter operations points points formatting variable functions operation.\n",
        "    # Show the current FPS on screen\n",
        "    fps_text = font.render(f\"FPS: {clock.get_fps():.1f}\", True, (255, 255, 255))\n",
        "    screen.blit(fps_text, (10, 10))\n",
        "\n",
        "    # 7. Render map display type updates object variable data values.\n",
        "    pygame.display.flip()\n",
        "    # 8. Set execution operations cap mappings target string array operations type variable checks.\n",
        "    clock.tick(60)  # Try changing this to 30 or 10 and see the difference!\n",
        "\n",
        "pygame.quit()\n",
        "print(\"FPS demo closed.\")\n"
    ],
    # 10. Sound
    [
        "# 1. Initialize objects arrays string array system array command variables array variable data operations checks commands variables the targets format system target loops strings values object type type.\n",
        "# Sound demo (conceptual — requires actual sound files)\n",
        "import pygame\n",
        "pygame.init()\n",
        "# 2. Ang module na sound ang initialize execution assignment logic targets parameters the strings parameter array process.\n",
        "pygame.mixer.init()\n",
        "\n",
        "print(\"Sound module initialized:\", pygame.mixer.get_init())\n",
        "\n",
        "# 3. Paano i play is load array operations points formatting values objects object type formatting variables function arrays operations types form parameters logic types loop mapped targets object process commands values maps memory objects operations logic type update form system conditions type values memory strings value the formatting.\n",
        "# To play a sound, you would do:\n",
        "# sound = pygame.mixer.Sound(\"path/to/sound.wav\")\n",
        "# sound.play()\n",
        "\n",
        "# 4. Same system mapping mapping format updates system loops array loops strings maps memory check commands map logic checks processes command logic format target mapping object parameters map variables arrays conditions value values process parameters updates parameter assignments execution process point updates condition variables maps mapping functions param.\n",
        "# To play background music:\n",
        "# pygame.mixer.music.load(\"path/to/music.mp3\")\n",
        "# pygame.mixer.music.play(-1)\n",
        "\n",
        "print(\"\\n(Add your own .wav or .mp3 files to test this!)\")\n",
        "pygame.quit()\n"
    ],
    # 11. Simple Animation
    [
        "# 1. Load module parameter array string values map formats.\n",
        "import pygame\n",
        "pygame.init()\n",
        "\n",
        "# 2. Paggawa interface logic array mappings condition array formats variables class type loops strings assignment type.\n",
        "class SimpleAnimator:\n",
        "    \"\"\"A simple sprite animator that cycles through a list of images.\"\"\"\n",
        "\n",
        "    def __init__(self, frame_paths, scale=2):\n",
        "        # 3. Load logic condition command format the object string map condition mappings parameter variable conditions command operations condition string param format values types formats parameters formats object format type formats variable loop update condition operations target loop string conditions variable operations format variables form operations parameter types mapped format arrays the mapping types process variable formatting string operations loop format memory string system parameter arrays target object variables parameter memory.\n",
        "        # Load all frame images into a list\n",
        "        self.frames = []\n",
        "        for path in frame_paths:\n",
        "            img = pygame.image.load(path).convert_alpha()\n",
        "            # Scale the image\n",
        "            img = pygame.transform.scale(img, (img.get_width() * scale, img.get_height() * scale))\n",
        "            # Remove background color\n",
        "            img.set_colorkey((112, 154, 209))\n",
        "            self.frames.append(img)\n",
        "\n",
        "        # 4. Starting object string formats logic assignments array mapping loop function type array command formats logic functions.\n",
        "        self.current_frame = 0\n",
        "\n",
        "    def update(self):\n",
        "        # 5. Logic commands mapping function variable form process command command checks value type parameter target values assignment map maps map loop variable formats logic mapping maps.\n",
        "        \"\"\"Advance to the next frame.\"\"\"\n",
        "        self.current_frame += 1\n",
        "        if self.current_frame >= len(self.frames):\n",
        "            self.current_frame = 0  # Loop back to the start\n",
        "\n",
        "    def draw(self, screen, x, y):\n",
        "        # 6. Iguhit sa arrays target parameters values tuple logic string mappings check memory variable value values check operation variables assignment formats the parameter values functions processes condition mapped assignment variables check value.\n",
        "        \"\"\"Draw the current frame on the screen.\"\"\"\n",
        "        screen.blit(self.frames[self.current_frame], (x, y))\n",
        "\n",
        "\n",
        "# 7. Object format mapping array assignment formats the assignment target command target logic mappings checks checks types formats condition string values type type value loop command loops variables loops variable data.\n",
        "# --- Usage ---\n",
        "screen = pygame.display.set_mode((800, 600))\n",
        "pygame.display.set_caption(\"Sprite Animation Demo\")\n",
        "clock = pygame.time.Clock()\n",
        "\n",
        "# Build a list of frame file paths\n",
        "# (Adjust these paths to match your actual sprite files)\n",
        "try:\n",
        "    # 8. Loop parameter parameter checks functions condition arrays format condition string target operations parameter command mappings object.\n",
        "    frames = [f\"assets/sprites/rayquaza/idle/rayquaza_{i}.png\" for i in range(11)]\n",
        "    animator = SimpleAnimator(frames)\n",
        "\n",
        "    running = True\n",
        "    while running:\n",
        "        for event in pygame.event.get():\n",
        "            if event.type == pygame.QUIT:\n",
        "                running = False\n",
        "\n",
        "        # 9. Execute check assignment function process values command loops logic parameters maps format the memory array the parameters update loops values strings strings assignment strings mapping array arrays conditions system string mappings check map loops strings maps mapping condition condition assignment target update logic format values memory array target string type format targets values strings memory check array target.\n",
        "        animator.update()  # Go to next frame\n",
        "\n",
        "        screen.fill((30, 30, 60))\n",
        "        animator.draw(screen, 300, 200)\n",
        "        pygame.display.flip()\n",
        "        clock.tick(14)  # 14 FPS for a classic sprite animation feel\n",
        "\n",
        "except FileNotFoundError as e:\n",
        "    print(f\"Sprite file not found: {e}\")\n",
        "    print(\"Make sure your sprite files exist in the correct path.\")\n",
        "\n",
        "pygame.quit()\n",
        "print(\"Animation demo closed.\")\n"
    ],
    # 12. Full program
    [
        "# 1. Initialize program object formats logic the string mappings system arrays type operations parameter format array memory values value strings the values target loops format loops mapped updates condition memory command mapping parameters values string mapping check functions logic loop.\n",
        "import pygame\n",
        "import sys\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 1. INITIALIZATION\n",
        "# ──────────────────────────────────────────────\n",
        "pygame.init()\n",
        "\n",
        "# Screen setup\n",
        "SCREEN_WIDTH  = 800\n",
        "SCREEN_HEIGHT = 600\n",
        "screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))\n",
        "pygame.display.set_caption(\"Pygame Fundamentals — Full Demo\")\n",
        "\n",
        "# Clock for frame rate control\n",
        "clock = pygame.time.Clock()\n",
        "FPS = 60\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 2. COLORS\n",
        "# ──────────────────────────────────────────────\n",
        "BG_COLOR   = (30, 30, 60)\n",
        "WHITE      = (255, 255, 255)\n",
        "COLORS     = [\n",
        "    (0, 200, 255),   # Cyan\n",
        "    (255, 80, 80),   # Red\n",
        "    (80, 255, 80),   # Green\n",
        "    (255, 200, 50),  # Gold\n",
        "    (200, 80, 255),  # Purple\n",
        "]\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 3. GAME STATE\n",
        "# ──────────────────────────────────────────────\n",
        "circle_x     = SCREEN_WIDTH // 2\n",
        "circle_y     = SCREEN_HEIGHT // 2\n",
        "circle_r     = 30\n",
        "speed        = 5\n",
        "color_index  = 0\n",
        "\n",
        "# Font for HUD text\n",
        "font = pygame.font.SysFont(\"Arial\", 22)\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 4. GAME LOOP\n",
        "# ──────────────────────────────────────────────\n",
        "running = True\n",
        "while running:\n",
        "\n",
        "    # ─── EVENT HANDLING ───\n",
        "    for event in pygame.event.get():\n",
        "        if event.type == pygame.QUIT:\n",
        "            running = False\n",
        "\n",
        "        if event.type == pygame.KEYDOWN:\n",
        "            if event.key == pygame.K_SPACE:\n",
        "                # Cycle through colors\n",
        "                color_index = (color_index + 1) % len(COLORS)\n",
        "            if event.key == pygame.K_ESCAPE:\n",
        "                running = False\n",
        "\n",
        "    # ─── CONTINUOUS INPUT (smooth movement) ───\n",
        "    keys = pygame.key.get_pressed()\n",
        "    if keys[pygame.K_LEFT]:\n",
        "        circle_x -= speed\n",
        "    if keys[pygame.K_RIGHT]:\n",
        "        circle_x += speed\n",
        "    if keys[pygame.K_UP]:\n",
        "        circle_y -= speed\n",
        "    if keys[pygame.K_DOWN]:\n",
        "        circle_y += speed\n",
        "\n",
        "    # Keep the circle on screen\n",
        "    circle_x = max(circle_r, min(SCREEN_WIDTH - circle_r, circle_x))\n",
        "    circle_y = max(circle_r, min(SCREEN_HEIGHT - circle_r, circle_y))\n",
        "\n",
        "    # ─── DRAWING ───\n",
        "    screen.fill(BG_COLOR)\n",
        "\n",
        "    # Draw the player circle\n",
        "    current_color = COLORS[color_index]\n",
        "    pygame.draw.circle(screen, current_color, (circle_x, circle_y), circle_r)\n",
        "\n",
        "    # Draw a UI panel at the bottom\n",
        "    pygame.draw.rect(screen, (50, 50, 80), (0, SCREEN_HEIGHT - 60, SCREEN_WIDTH, 60))\n",
        "\n",
        "    # Render HUD text\n",
        "    hud = font.render(\n",
        "        f\"Position: ({circle_x}, {circle_y})  |  Color: {color_index+1}/{len(COLORS)}  |  FPS: {clock.get_fps():.0f}\",\n",
        "        True, WHITE\n",
        "    )\n",
        "    screen.blit(hud, (20, SCREEN_HEIGHT - 42))\n",
        "\n",
        "    instructions = font.render(\"Arrow Keys = Move  |  Space = Change Color  |  Esc = Quit\", True, (180, 180, 180))\n",
        "    screen.blit(instructions, (20, 15))\n",
        "\n",
        "    # ─── FLIP & TICK ───\n",
        "    pygame.display.flip()\n",
        "    clock.tick(FPS)\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 5. CLEANUP\n",
        "# ──────────────────────────────────────────────\n",
        "pygame.quit()\n",
        "print(\"Full demo ended. Great job completing the tutorial!\")\n"
    ]
]


with open(NOTEBOOK_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

code_cells = [cell for cell in nb['cells'] if cell['cell_type'] == 'code']

for i in range(min(len(new_sources), len(code_cells))):
    code_cells[i]["source"] = new_sources[i]

with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Done updating!")
